# code:language=ansible
---
- name: Install Nextcloud on Debian 12
  tags:
    - never
    - install
  block:
    - name: Update and upgrade system packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - nginx
          - mariadb-server
          - php-fpm
          - php-mysql
          - php-xml
          - php-mbstring
          - php-curl
          - php-gd
          - php-zip
          - php-intl
          - php-bz2
          - unzip
          - bzip2
          - curl
          - php-imagick
          - python3-pymysql
          - sudo
          - php-cli
        state: present

    - name: Create Nextcloud database
      community.mysql.mysql_db:
        name: "{{ nextcloud_db_name }}"
        state: present
        login_unix_socket: "{{ nextcloud_mysql_login_socket }}"

    - name: Create Nextcloud database user
      community.mysql.mysql_user:
        name: "{{ nextcloud_db_user }}"
        password: "{{ nextcloud_db_password }}"
        priv: "{{ nextcloud_db_name }}.*:ALL"
        state: present
        login_unix_socket: "{{ nextcloud_mysql_login_socket }}"

    - name: Download and extract Nextcloud
      ansible.builtin.unarchive:
        src: "{{ nextcloud_url }}"
        dest: "{{ nextcloud_default_path }}/nextcloud"
        owner: "{{ nextcloud_web_user }}"
        group: "{{ nextcloud_web_user }}"
        remote_src: true
        mode: "0755"
      when: nextcloud_url is defined

    - name: Set permissions
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ nextcloud_web_user }}"
        group: "{{ nextcloud_web_user }}"
        mode: "0755"
        recurse: true
      loop:
        - "{{ nextcloud_root }}"
        - "{{ nextcloud_root }}/config"

    - name: Ensure Nginx sites directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/nginx/sites-available
        - /etc/nginx/sites-enabled

    - name: Configure Nginx server block
      ansible.builtin.template:
        src: nextcloud.conf.j2
        dest: "{{ nextcloud_nginx_sites_available }}nextcloud"
        mode: '0644'
      notify: Restart Nginx

    - name: Enable Nextcloud Nginx site
      ansible.builtin.file:
        src: "{{ nextcloud_nginx_sites_available }}nextcloud"
        dest: "{{ nextcloud_nginx_sites_enabled }}nextcloud"
        state: link
        force: true

    - name: Remove default Nginx site
      ansible.builtin.file:
        path: "{{ nextcloud_nginx_sites_enabled }}default"
        state: absent
      notify: Restart Nginx

    - name: Restart PHP-FPM
      ansible.builtin.service:
        name: php8.2-fpm
        state: restarted

    - name: Verify Nextcloud installation
      ansible.builtin.stat:
        path: "{{ nextcloud_root }}/occ"
      register: nextcloud_occ

    - name: Run Nextcloud CLI installation
      ansible.builtin.command: >
        sudo -u {{ nextcloud_web_user }} php {{ nextcloud_root }}/occ maintenance:install
        --database "mysql" --database-name "{{ nextcloud_db_name }}"
        --database-user "{{ nextcloud_db_user }}" --database-pass "{{ nextcloud_db_password }}"
        --admin-user "{{ nextcloud_admin_user }}" --admin-pass "{{ nextcloud_admin_password }}"
      args:
        chdir: "{{ nextcloud_root }}"
      register: run_nextcloud
      changed_when: run_nextcloud.rc != 0
      when: nextcloud_occ.stat.exists
