# code:language=ansible
---
- name: Install Nextcloud on Debian 12
  tags:
    - never
    - install
  block:
    - name: Update and upgrade system packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - nginx
          - mariadb-server
          - php-fpm
          - php-mysql
          - php-xml
          - php-mbstring
          - php-curl
          - php-gd
          - php-zip
          - php-intl
          - php-bz2
          - unzip
          - bzip2
          - curl
          - php-imagick
          - python3-pymysql
        state: present

    - name: Create Nextcloud database
      community.mysql.mysql_db:
        name: "{{ nextcloud_db_name }}"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Create Nextcloud database user
      community.mysql.mysql_user:
        name: "{{ nextcloud_db_user }}"
        password: "{{ nextcloud_db_password }}"
        priv: "{{ nextcloud_db_name }}.*:ALL"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Download Nextcloud
      ansible.builtin.get_url:
        url: "{{ nextcloud_url }}"
        dest: /tmp/nextcloud.tar.bz2
        mode: '0644'

    - name: Extract Nextcloud
      ansible.builtin.unarchive:
        src: /tmp/nextcloud.tar.bz2
        dest: /var/www/html/
        remote_src: true
        owner: "{{ web_user }}"
        group: "{{ web_user }}"

    - name: Set permissions
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ web_user }}"
        group: "{{ web_user }}"
        mode: "0755"
        recurse: true
      loop:
        - "{{ nextcloud_root }}"
        - "{{ nextcloud_root }}/config"

    - name: Configure Nginx server block
      ansible.builtin.template:
        src: nextcloud.conf.j2
        dest: /etc/nginx/sites-available/nextcloud
        mode: '0644'
      notify: Restart Nginx

    - name: Linking nextcloud sites
      ansible.builtin.file:
        src: /etc/nginx/sites-available/nextcloud
        dest: /etc/nginx/sites-enabled/nextcloud
        state: link

    - name: Remove default Nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart Nginx

    - name: Restart PHP-FPM
      ansible.builtin.service:
        name: php8.2-fpm
        state: restarted

    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

    - name: Run Nextcloud CLI installation
      ansible.builtin.command: >
        sudo -u {{ web_user }} php {{ nextcloud_root }}/occ maintenance:install
        --database "mysql" --database-name "{{ nextcloud_db_name }}"
        --database-user "{{ nextcloud_db_user }}" --database-pass "{{ nextcloud_db_password }}"
        --admin-user "{{ nextcloud_admin_user }}" --admin-pass "{{ nextcloud_admin_password }}"
      args:
        chdir: "{{ nextcloud_root }}"
      register: run_nextcloud
      changed_when: run_nextcloud.rc != 0
