# code:language=ansible
---
- name: Including tasks to install nextcloud
  ansible.builtin.include_tasks: install_nextcloud.yml
  tags:
    - never
    - install

- name: Deploying scritps to the server
  ansible.builtin.include_tasks: deploy_scripts.yml
  tags:
    - never
    - deploy_scripts
