services:
  db:
    container_name: mariadb
    image: mariadb:10.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Nextcloud2024@%
      - MYSQL_PASSWORD=Nextcloud2024@%
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    container_name: redis
    image: redis:alpine
    restart: always

  app:
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    depends_on:
      - redis
      - db
    volumes:
      - /mnt/data/nextcloud:/var/www/html
      - /mnt/data/backups:/mnt/data/backups
    environment:
      - MYSQL_PASSWORD=Nextcloud2024@%
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - PHP_UPLOAD_LIMIT=10G
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_MAX_FILESIZE=10G
      - PHP_POST_MAX_SIZE=10G

volumes:
  nextcloud:
  db: