services:
  db:
    container_name: mariadb
    image: mariadb:10.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Nextcloud2024@%
      - MYSQL_PASSWORD=Nextcloud2024@%
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  # pgdb:
  #   container_name: postgres
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_DB=nextcloud
  #     - POSTGRES_USER=nextcloud
  #     - POSTGRES_PASSWORD=Nextcloud2024@%
  #   volumes:
  #     - pgdb:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  redis:
    container_name: redis
    image: redis:alpine
    restart: always

  app:
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    depends_on:
      - redis
      - db
      - pgdb
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud/custom-php/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    environment:
      - MYSQL_PASSWORD=Nextcloud2024@%
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - PHP_UPLOAD_LIMIT=10G
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_MAX_FILESIZE=10G
      - PHP_POST_MAX_SIZE=10G

volumes:
  nextcloud:
  db:
  pgdb:
